### PR TITLE
Remove All Missing Episodes On Refresh

### PR DESCRIPTION
**Pull request by scampower3**

### CODE REVIEW

**Comment by scampower3** [comment]
@Shadowghost If you can, can you take a look at [this](https://github.com/Shadowghost/jellyfin/blob/a475a7d50a1ed5b7de4cb66db0a5e0cab60ece0d/MediaBrowser.Providers/TV/SeriesMetadataService.cs#L212-L216). This section of the code sets the virtual season created by the missing episode provider from IsVirtualItem=true to IsVirtualItem=false. Which results in ghost seasons when "Display missing episodes within their series" is unchecked.

**Comment by scampower3** [comment]
@crobibero Can be released so users don't have to rebuild their entire shows lib for this [issue](https://github.com/jellyfin/jellyfin/issues/12208)

**Review by Shadowghost — APPROVED** [review]
I'm currently unable to test anything since my own environment is down for the next weeks due to maintenance.
Quite sure that I wasn't the one implementin this virtual -> non-virtual season translation.

**Comment by scampower3** [comment]
It's part of [this pr](https://github.com/jellyfin/jellyfin/pull/12050). If you can give a brief explanation, I'll try see if I can do smth about it without buring JF down.😅

**Comment by sjorge** [comment]
> It's part of [this pr](https://github.com/jellyfin/jellyfin/pull/12050). If you can give a brief explanation, I'll try see if I can do smth about it without burning JF down.😅

Both parts of that have been reverted (sadly causing my issue to resurface)

https://github.com/jellyfin/jellyfin/pull/12356
And
https://github.com/jellyfin/jellyfin/pull/12240

So there is no trace left of the above linked PR in 10.9.9

**Review by crobibero — APPROVED** [review]

**Pull request merged**
