### PR TITLE
TVDB search fix

### PR DESCRIPTION
**Pull request by Larvitar**
Copy of [#4159](https://github.com/jellyfin/jellyfin/pull/4159)

Fixes several issues with TVDB plugin series search. TVDB would never run a "name only" search in `GetSearchResults` and `GetMetadata` for short series names would often return wrong results.

**Changes**
1. `IsValidSeries` always returned `true` for `SeriesInfo` object in `GetSearchResults`. 
2. Never include year in search name as TVDB tends to get confused by it (see #4132).
3. Improve search result sorting.

**Issues**
Fixes [#4132](https://github.com/jellyfin/jellyfin/issues/4132)

### CODE REVIEW

**Comment by crobibero** [comment]
Sorry, I snuck in a change while you were migrating the PR! Thankfully it's only a style fix :)

**Comment by Larvitar** [comment]
I should have checked it though. I'll resolve it in a minute :)

**Review by crobibero — APPROVED** [review]

**Comment by Larvitar** [comment]
BTW. I've noticed you've changed some instances of `TvdbPlugin.ProviderName` to `MetadataProvider.Tvdb` in d4b5b555f7774fa98864be9f959f5fc422e6ba4f . Was this intentional?

**Comment by crobibero** [comment]
Yes, as we move providers away from server I've been setting the ProviderName to something that doesn't rely on server. 
It's the same string so the end result will be the same

**Comment by Larvitar** [comment]
That's why I'm asking. `MetadataProvider.Tvdb` relies on the server. You've changed it to `TvdbPlugin.ProviderName` in the initial version of plugin but reverted 2 lines in d4b5b55 . Now we use both values in `TvdbSeriesProvider.cs`.

**Comment by crobibero** [comment]
Fixed in master, thanks for catching that!

**Pull request merged**
