### PR TITLE
Add support for regional, alternate, altdvd orders

### PR DESCRIPTION
**Pull request by scampower3**
Fixes: https://github.com/jellyfin/jellyfin-plugin-tvdb/issues/49
Requires: https://github.com/jellyfin/jellyfin-web/pull/5505

### CODE REVIEW

**Comment by scampower3** [comment]
Can be merged before web changes.

**Comment by scampower3** [comment]
Here's a simple userscript to inject the options if the web changes are not merged. Replace [protocal] with http or https and replace [url] with your ip+port or domain of Jellyfin.

To be used with any user script manager like tampermonkey or greasemonkey.

```
// ==UserScript==
// @name         Tvdb Display Order Options Injector
// @namespace    http://tampermonkey.net/
// @version      2024-05-17
// @description  Adds missing Tvdb Display Order in Jellyfin.
// @author       scampower3
// @match        [protocal]://[url]/web/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=greasyfork.org
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    console.log("Tvdb Display Order Options Injector Script loaded");
    /**Setup Event Listeners */
    document.addEventListener('viewshow', viewShowEvent)

    // Mutation Observer
    const observer = new MutationObserver(injectDisplayOrderOptions);
    // Only observe when on tv.html, details, home.html, or search.html
    observer.disconnect();

    function viewShowEvent(){
        const location = window.location.hash;
        console.debug("Current: " + location);
        if (location.startsWith('#/tv.html') || location.startsWith('#/details') || location.startsWith('#/home.html') || location.startsWith('#/search.html')){
            console.debug('Connecting Observer');
            observer.observe(document.body, {childList: true, subtree: true});
        }
        else{
            console.debug('Disconnecting Observer');
            observer.disconnect();
        }
    }

    function injectDisplayOrderOptions(MutationList, observer){
        console.debug("Mutation Observer Triggered");
        const selectDisplayOrder = document.getElementById('selectDisplayOrder');

        if (!selectDisplayOrder){
            console.debug('selectDisplayOrder not found');
            return;
        }
        console.debug('selectDisplayOrder found');
        console.debug('Injecting Options')
        observer.disconnect();
        const options = [
            {value: 'alternate', text: 'Alternate'},
            {value: 'regional', text: 'Regional'},
            {value: 'altdvd', text: 'Alternate DVD'}
        ]
        //check if options already exist
        if (selectDisplayOrder.options.length > 8){
            console.debug('Options already exist');
            observer.observe(document.body, {childList: true, subtree: true});
            return;
        }
        options.forEach(option => {
            const optionElement = document.createElement('option');
            optionElement.value = option.value;
            optionElement.text = option.text;
            selectDisplayOrder.appendChild(optionElement);
        });
        observer.observe(document.body, {childList: true, subtree: true});
    }
})();
```

**Review by Shadowghost — APPROVED** [review]

**Comment by Blazeflack** [comment]
@scampower3 I don't suppose your nifty user-script will work on Jellyfin 10.8.11? I am sadly forced to stick with that version as I use Jellyfin on a Synology NAS and want to use hardware transcoding.

**Comment by scampower3** [comment]
Should work just fine, but the extra options that the script adds is for Tvdb v12

**Comment by onivlis38** [comment]
I'm a bit confused here, if I want to use TVDBs alternate order, do I need to use this script, or are the changes already in the plugin itself?

**Comment by scampower3** [comment]
Need to use the script until Jellyfin 10.10 is released

**Comment by jonas04anderberg** [comment]
Hi! Have something changed here recently? I tried the script a few days ago and it worked flawlessly. Now all of a sudden it just goes back to "Aired" immediately after i choose "Alternate" or the other options the the script gives. Does anybody else have the same problem?

**Pull request merged**
